Numero = int(input("Digite o numero que deseja multiplicar na tabuada: "))
print("----------------------------------------------------------------------------------")
print(f"1 x {Numero} = {1 * Numero}")
print(f"2 x {Numero} = {2 * Numero}")
print(f"3 x {Numero} = {3 * Numero}")
print(f"4 x {Numero} = {4 * Numero}")
print(f"5 x {Numero} = {5 * Numero}")
print(f"6 x {Numero} = {6 * Numero}")
print(f"7 x {Numero} = {7 * Numero}")
print(f"8 x {Numero} = {8 * Numero}")
print(f"9 x {Numero} = {9 * Numero}")
print(f"10 x {Numero} = {10 * Numero}")
print("----------------------------------------------------------------------------------")

